services:

  - type: web
    name: sic-xe-web
    runtime: node
    plan: free
    region: oregon

    rootDir: frontend

    buildCommand: npm ci && npm run build
    startCommand: npm start

    envVars:
      - key: SIMULATOR_API_URL
        value: https://sic-xe-engine.onrender.com


  - type: web
    name: sic-xe-engine
    runtime: docker
    plan: free
    region: oregon

    dockerfilePath: backend/Dockerfile.vercel
    dockerContext: backend